
(function(){
'use strict';
const VERSION='V546.30 CLEAN TEST BACKUP REAL';
const KEYS=['OFICINAOS_STATE_MASTER','OFICINAOS_STATE_V546_30','OFICINAOS_STATE','oficinaos_state','STATE'];
function uid(p){return p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)}
function today(){return new Date().toISOString().slice(0,10)}
function num(v){if(window.OFICINAOS_NUM)return window.OFICINAOS_NUM(v);if(v===null||v===undefined||v==='')return 0;if(typeof v==='string')v=v.replace(/R\$/g,'').replace(/\s/g,'').replace(/\./g,'').replace(',','.');v=Number(v);return Number.isFinite(v)?v:0}
function money(v){return num(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function jget(k,f){try{return JSON.parse(localStorage.getItem(k)||'')}catch(e){return f}}
function jset(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){console.warn('storage',k,e)}}
function txt(sel){try{const e=document.querySelector(sel);return e?String(e.value||e.textContent||'').trim():''}catch(e){return ''}}
function empty(){return {meta:{versao:VERSION,criadoEm:new Date().toISOString()},config:jget('oficinaos_config',{}),clientes:[],veiculos:[],orcamentos:[],agenda:[],financeiro:{lancamentos:[],receitas:[],despesas:[],receber:[],pagar:[]},contas:{},metas:{objetivos:{faturamento:15000,margem:25,ticketMedio:1800}},relatorios:{},ia:{historico:[],contexto:[],modo:'consulta'},materiais:[],fotos:[]}}
function tx(t){const raw=String(t.tipo||t.type||'').toLowerCase(),tipo=(raw==='dep'||raw.includes('desp'))?'despesa':'receita',valor=num(t.valor!==undefined?t.valor:t.val),rs=String(t.status||t.paid||'').toLowerCase(),status=rs.includes('pago')&&!rs.includes('não')?'pago':'pendente';return {id:String(t.id||uid('tx')),tipo,type:tipo==='receita'?'rec':'dep',categoria:t.categoria||t.cat||'Outros',cat:t.categoria||t.cat||'Outros',descricao:t.descricao||t.desc||'',desc:t.descricao||t.desc||'',data:t.data||t.date||today(),date:t.data||t.date||today(),valor,val:valor,status,paid:status==='pago'?'Pago':'Não pago',origem:t.origem||'financeiro',clienteId:t.clienteId||'',veiculoId:t.veiculoId||'',orcamentoId:t.orcamentoId||'',agendaId:t.agendaId||''}}
function rebuild(s){s.financeiro=s.financeiro||{lancamentos:[]};s.financeiro.lancamentos=(s.financeiro.lancamentos||[]).map(tx);const ids=new Set();s.financeiro.lancamentos=s.financeiro.lancamentos.filter(x=>{if(ids.has(x.id))return false;ids.add(x.id);return true});s.financeiro.receitas=s.financeiro.lancamentos.filter(x=>x.tipo==='receita');s.financeiro.despesas=s.financeiro.lancamentos.filter(x=>x.tipo==='despesa');s.financeiro.receber=s.financeiro.receitas.filter(x=>x.status!=='pago');s.financeiro.pagar=s.financeiro.despesas.filter(x=>x.status!=='pago');s.contas={pagar:s.financeiro.pagar,pagas:s.financeiro.despesas.filter(x=>x.status==='pago'),pendentes:s.financeiro.lancamentos.filter(x=>x.status!=='pago')}}
function importFinanceiro(s){let a=[];['ALL_TX','oficinaos_ALL_TX','oficinaos_financeiro_lancamentos','financeiro_lancamentos','lancamentos'].forEach(k=>{const v=jget(k,[]);if(Array.isArray(v))a=a.concat(v)});const ids=new Set((s.financeiro.lancamentos||[]).map(x=>String(x.id)));a.map(tx).forEach(t=>{if(!ids.has(t.id)){s.financeiro.lancamentos.push(t);ids.add(t.id)}})}
function upCli(s,o){const nome=(o.nome||o.cliente||'Cliente').trim(),tel=(o.telefone||o.whatsapp||'').trim(),doc=(o.documento||o.cpf||o.cnpj||'').trim();let c=s.clientes.find(x=>(doc&&x.documento===doc)||(tel&&x.telefone===tel)||x.nome===nome);if(!c){c={id:o.id||uid('cli'),nome,telefone:tel,documento:doc,email:o.email||'',status:o.status||'ativo',historico:o.historico||[],origem:o.origem||'state',criadoEm:new Date().toISOString()};s.clientes.push(c)}else{c.historico=c.historico||[]}return c}
function upVei(s,cid,o){const modelo=(o.modelo||o.veiculo||'').trim(),placa=(o.placa||'').trim();let v=s.veiculos.find(x=>x.clienteId===cid&&((placa&&x.placa===placa)||(modelo&&x.modelo===modelo)));if(!v){v={id:o.id||uid('vei'),clienteId:cid,modelo,placa,cor:o.cor||'',ano:o.ano||'',criadoEm:new Date().toISOString()};s.veiculos.push(v)}return v}
function importList(s){['oficinaos_clientes','CLIENTES','clientes','oficinaos_crm_clientes','crm_clientes'].forEach(k=>{const a=jget(k,[]);if(Array.isArray(a))a.forEach(c=>upCli(s,{...c,nome:c.nome||c.name||c.cliente,origem:k}))});['oficinaos_agenda','AGENDA','agenda','oficinaos_os','OS_LIST','agenda_os'].forEach(k=>{const a=jget(k,[]);if(Array.isArray(a))a.forEach(o=>{const os={id:String(o.id||uid('os')),clienteId:o.clienteId||'',veiculoId:o.veiculoId||'',orcamentoId:o.orcamentoId||'',cliente:o.cliente||o.nomeCliente||'Cliente',veiculo:o.veiculo||o.modelo||'',servico:o.servico||o.descricao||'Serviço',valor:num(o.valor||o.total),status:o.status||o.situacao||'agendado',etapa:o.etapa||o.etapaAtual||'Entrada',entrada:o.entrada||o.data||today(),entregaPrevista:o.entregaPrevista||o.prazo||'',etapas:o.etapas||[],fotos:o.fotos||[],historico:o.historico||[],origem:k};if(!s.agenda.some(x=>x.id===os.id))s.agenda.push(os)})});['oficinaos_orcamentos','ORCAMENTOS','orcamentos','historico_orcamentos','oficinaos_historico_orcamentos'].forEach(k=>{const a=jget(k,[]);if(Array.isArray(a))a.forEach(o=>{const orc={id:String(o.id||o.numero||uid('orc')),clienteId:o.clienteId||'',veiculoId:o.veiculoId||'',cliente:o.cliente||o.nomeCliente||'Cliente',veiculo:o.veiculo||o.modelo||'',servico:o.servico||o.descricao||'Serviço',valor:num(o.valor||o.total||o.totalFinal),status:o.status||o.situacao||'aberto',prazo:o.prazo||o.dataPrevista||'',criadoEm:o.criadoEm||new Date().toISOString(),origem:k};if(!s.orcamentos.some(x=>x.id===orc.id))s.orcamentos.push(orc)})})}
function link(s){s.clientes.forEach(c=>c.historico=c.historico||[]);s.agenda.forEach(os=>{let c=os.clienteId?s.clientes.find(x=>x.id===os.clienteId):s.clientes.find(x=>x.nome===os.cliente);if(!c)c=upCli(s,{nome:os.cliente});os.clienteId=c.id;if(!c.historico.some(h=>h.agendaId===os.id))c.historico.push({data:os.entrada||today(),tipo:'os',agendaId:os.id,descricao:os.servico,valor:os.valor,status:os.status});(os.fotos||[]).forEach(f=>{if(!c.historico.some(h=>h.fotoId===f.id))c.historico.push({data:f.criadaEm||today(),tipo:'foto_os',agendaId:os.id,fotoId:f.id,etapa:f.etapa||os.etapa,descricao:f.nome||'Foto'})})});s.orcamentos.forEach(o=>{let c=o.clienteId?s.clientes.find(x=>x.id===o.clienteId):s.clientes.find(x=>x.nome===o.cliente);if(!c)c=upCli(s,{nome:o.cliente});o.clienteId=c.id;if(!c.historico.some(h=>h.orcamentoId===o.id))c.historico.push({data:o.criadoEm||today(),tipo:'orcamento',orcamentoId:o.id,descricao:o.servico,valor:o.valor,status:o.status})});s.financeiro.lancamentos.forEach(t=>{if(t.clienteId){const c=s.clientes.find(x=>x.id===t.clienteId);if(c&&!c.historico.some(h=>h.txId===t.id))c.historico.push({data:t.data,tipo:'financeiro',txId:t.id,descricao:t.descricao,valor:t.valor,status:t.status})}})}
function resumo(s){rebuild(s);const receitas=s.financeiro.receitas.reduce((a,b)=>a+num(b.valor),0),despesas=s.financeiro.despesas.reduce((a,b)=>a+num(b.valor),0),rp=s.financeiro.receitas.filter(x=>x.status==='pago').reduce((a,b)=>a+num(b.valor),0),dp=s.financeiro.despesas.filter(x=>x.status==='pago').reduce((a,b)=>a+num(b.valor),0),osTotal=s.agenda.length,osEntregues=s.agenda.filter(x=>String(x.status).toLowerCase().includes('entreg')).length,ticket=osEntregues?rp/osEntregues:(s.financeiro.receitas.length?receitas/s.financeiro.receitas.length:0),margem=receitas?((receitas-despesas)/receitas*100):0;const r={data:new Date().toISOString(),receitas,despesas,resultado:receitas-despesas,receitasPagas:rp,despesasPagas:dp,resultadoPago:rp-dp,osTotal,osEntregues,ticketMedio:ticket,margem,clientes:s.clientes.length,orcamentos:s.orcamentos.length};s.relatorios={resumos:[r],ultimoResumo:r};s.metas=s.metas||{};s.metas.objetivos=s.metas.objetivos||{faturamento:15000,margem:25,ticketMedio:1800};s.metas.realizado={faturamento:rp||receitas,margem,ticketMedio:ticket,osEntregues,resultado:receitas-despesas};s.ia=s.ia||{};s.ia.modo='consulta';s.ia.contexto=[{tipo:'state_master',dados:r,atualizadoEm:new Date().toISOString()}]}
function syncState(){let s=jget('OFICINAOS_STATE_MASTER',null)||jget('OFICINAOS_STATE_V546_30',null)||jget('OFICINAOS_STATE',null)||jget('oficinaos_state',null)||jget('STATE',null)||empty();s.clientes=s.clientes||[];s.veiculos=s.veiculos||[];s.orcamentos=s.orcamentos||[];s.agenda=s.agenda||[];s.financeiro=s.financeiro||{lancamentos:[]};s.financeiro.lancamentos=s.financeiro.lancamentos||[];importFinanceiro(s);importList(s);link(s);resumo(s);s.meta=s.meta||{};s.meta.versao=VERSION;s.meta.atualizadoEm=new Date().toISOString();KEYS.forEach(k=>jset(k,s));jset('oficinaos_financeiro_lancamentos',s.financeiro.lancamentos);jset('ALL_TX',s.financeiro.lancamentos.map(t=>({id:t.id,type:t.type,cat:t.categoria,desc:t.descricao,date:t.data,val:t.valor,paid:t.paid,clienteId:t.clienteId,orcamentoId:t.orcamentoId,agendaId:t.agendaId,origem:t.origem})));window.OFICINAOS_STATE=s;return s}
function saveState(s){link(s);resumo(s);s.meta=s.meta||{};s.meta.versao=VERSION;s.meta.atualizadoEm=new Date().toISOString();KEYS.forEach(k=>jset(k,s));window.OFICINAOS_STATE=s;return s}
function readCli(){return {nome:txt('input[placeholder*="cliente" i],input[placeholder*="nome" i],#cliente,#nome,#nomeCliente')||'Cliente',telefone:txt('input[placeholder*="telefone" i],input[placeholder*="whatsapp" i],#telefone,#whatsapp'),documento:txt('input[placeholder*="cpf" i],input[placeholder*="cnpj" i],#cpf,#cnpj,#documento')}}
function readVei(){return {modelo:txt('input[placeholder*="veículo" i],input[placeholder*="veiculo" i],input[placeholder*="modelo" i],#veiculo,#modelo,#orcVeiculo'),placa:txt('input[placeholder*="placa" i],#placa')}}
function clienteParaOrcamento(){const s=syncState(),c=upCli(s,readCli()),v=upVei(s,c.id,readVei());jset('OFICINAOS_DRAFT_ORCAMENTO',{cliente:c,veiculo:v,criadoEm:new Date().toISOString()});saveState(s);alert('Cliente e veículo enviados para o Orçamento.');location.href='orcamento.html'}
function preencherOrcamento(){const d=jget('OFICINAOS_DRAFT_ORCAMENTO',null);if(!d)return;[['input[placeholder*="cliente" i],#cliente,#orcCliente',d.cliente&&d.cliente.nome],['input[placeholder*="telefone" i],input[placeholder*="whatsapp" i],#telefone,#whatsapp',d.cliente&&d.cliente.telefone],['input[placeholder*="veículo" i],input[placeholder*="veiculo" i],input[placeholder*="modelo" i],#veiculo,#modelo,#orcVeiculo',d.veiculo&&d.veiculo.modelo],['input[placeholder*="placa" i],#placa',d.veiculo&&d.veiculo.placa]].forEach(([sel,val])=>{if(!val)return;const el=document.querySelector(sel);if(el&&'value'in el){el.value=val;el.dispatchEvent(new Event('input',{bubbles:true}))}})}
function aprovarOrcamento(){const s=syncState(),c=upCli(s,readCli()),v=upVei(s,c.id,readVei()),body=document.body?document.body.innerText:'',vals=[...body.matchAll(/R\$\s*([\d\.\,]+)/g)].map(m=>num(m[1])).filter(x=>x>0),valor=vals.length?vals[vals.length-1]:0,servico=txt('textarea,#descricao,#servico,input[placeholder*="serviço" i]')||'Serviço aprovado';const orc={id:uid('orc'),clienteId:c.id,veiculoId:v.id,cliente:c.nome,veiculo:v.modelo,servico,valor,status:'aprovado',prazo:txt('input[type="date"],#prazo,#dataPrevista')||today(),origem:'orcamento',criadoEm:new Date().toISOString()};s.orcamentos.push(orc);s.financeiro.lancamentos.push({id:'tx_'+orc.id,tipo:'receita',type:'rec',categoria:'Orçamento aprovado',descricao:c.nome+' — '+servico,data:today(),valor,status:'pendente',paid:'Não pago',origem:'orcamento',clienteId:c.id,veiculoId:v.id,orcamentoId:orc.id});s.agenda.push({id:'os_'+orc.id,clienteId:c.id,veiculoId:v.id,orcamentoId:orc.id,cliente:c.nome,veiculo:v.modelo,servico,valor,status:'agendado',etapa:'Entrada',entrada:today(),entregaPrevista:orc.prazo,etapas:[],fotos:[],historico:[{data:new Date().toISOString(),evento:'OS criada a partir do orçamento'}],origem:'orcamento'});saveState(s);alert('Orçamento aprovado: receita pendente e OS criadas.')}
function agendaEntregue(){const s=syncState();let os=s.agenda[s.agenda.length-1];if(!os){os={id:uid('os'),cliente:'Cliente',servico:'Serviço',valor:0,status:'entregue',historico:[]};s.agenda.push(os)}os.status='entregue';os.etapa='Entregue';os.entregueEm=new Date().toISOString();let t=s.financeiro.lancamentos.find(x=>x.orcamentoId===os.orcamentoId||x.agendaId===os.id);if(!t&&os.valor)s.financeiro.lancamentos.push({id:'tx_os_'+os.id,tipo:'receita',type:'rec',categoria:'OS entregue',descricao:(os.cliente||'Cliente')+' — '+(os.servico||'Serviço'),data:today(),valor:os.valor,status:'pendente',paid:'Não pago',origem:'agenda',agendaId:os.id,clienteId:os.clienteId||''});saveState(s);alert('OS sincronizada com Financeiro e Clientes.')}
function painelResumo(){const s=syncState(),r=s.relatorios.ultimoResumo;alert('STATE MASTER OficinaOS\\nClientes: '+s.clientes.length+'\\nOrçamentos: '+s.orcamentos.length+'\\nOS: '+s.agenda.length+'\\nReceitas: '+money(r.receitas)+'\\nDespesas: '+money(r.despesas)+'\\nResultado: '+money(r.resultado))}
function inject(){if(document.getElementById('oficinaosStateMasterBridge'))return;const page=(location.pathname.split('/').pop()||'').toLowerCase(),b=document.createElement('div');b.id='oficinaosStateMasterBridge';b.style.cssText='position:fixed;right:12px;bottom:12px;z-index:999999;background:#fffaf4;border:1px solid #dcb990;border-radius:12px;padding:8px;display:flex;gap:6px;flex-wrap:wrap;box-shadow:0 2px 14px #0002;font:12px Arial';let h='<button onclick="OFICINAOS_STATE_MASTER.syncState()">🔄 Sincronizar STATE</button><button onclick="OFICINAOS_STATE_MASTER.painelResumo()">🔗 STATE</button>';if(page.includes('cliente'))h+='<button onclick="OFICINAOS_STATE_MASTER.clienteParaOrcamento()">Cliente → Orçamento</button>';if(page.includes('orcamento'))h+='<button onclick="OFICINAOS_STATE_MASTER.aprovarOrcamento()">Aprovar → Financeiro + Agenda</button>';if(page.includes('agenda'))h+='<button onclick="OFICINAOS_STATE_MASTER.agendaEntregue()">Entregar → Financeiro</button>';h+='<button onclick="location.href=\\'index.html\\'">Painel</button>';b.innerHTML=h;document.body.appendChild(b)}
window.OFICINAOS_STATE_MASTER={syncState,saveState,clienteParaOrcamento,preencherOrcamento,aprovarOrcamento,agendaEntregue,painelResumo};window.OFICINAOS_STATE_LAYER=window.OFICINAOS_STATE_MASTER;
document.addEventListener('DOMContentLoaded',()=>{syncState();inject();if(location.pathname.toLowerCase().includes('orcamento'))preencherOrcamento()});

window.OFICINAOS_LIMPAR_TUDO_TESTE = function(){
  if(prompt('Digite LIMPAR para apagar todos os dados locais de teste') !== 'LIMPAR') return;
  Object.keys(localStorage).forEach(function(k){
    if(k.toLowerCase().includes('oficinaos') || k === 'ALL_TX' || k === 'STATE' || k === 'CLIENTES' || k === 'AGENDA' || k === 'ORCAMENTOS'){
      localStorage.removeItem(k);
    }
  });
  alert('Ambiente limpo. Agora importe o backup real.');
  location.reload();
};

})();
