
(function(){
'use strict';
const VERSION='V546.32 REAL CORE';
const KEY='OFICINAOS_STATE_REAL_CORE';
const ALL_KEYS=['OFICINAOS_STATE_REAL_CORE','OFICINAOS_STATE_REAL','OFICINAOS_STATE_MASTER','OFICINAOS_STATE','oficinaos_state','STATE'];
function uid(p){return p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)}
function today(){return new Date().toISOString().slice(0,10)}
function n(v){if(v===null||v===undefined||v==='')return 0;if(typeof v==='string')v=v.replace(/R\$/g,'').replace(/\s/g,'').replace(/\./g,'').replace(',','.');v=Number(v);return Number.isFinite(v)?v:0}
function money(v){return n(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function get(k,f){try{return JSON.parse(localStorage.getItem(k)||'')}catch(e){return f}}
function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function empty(){return {meta:{version:VERSION,updatedAt:new Date().toISOString()},config:get('oficinaos_config',{}),clientes:[],veiculos:[],orcamentos:[],agenda:[],financeiro:{lancamentos:[],receitas:[],despesas:[],receber:[],pagar:[]},metas:{objetivos:{faturamento:15000,margem:25,ticketMedio:1800},realizado:{}},relatorios:{ultimoResumo:{}},ia:{contexto:[],historico:[]}}}
function tx(x){const raw=String(x.tipo||x.type||'').toLowerCase();const tipo=(raw==='dep'||raw.includes('despesa'))?'despesa':'receita';const valor=n(x.valor!==undefined?x.valor:x.val);const st=String(x.status||x.paid||'').toLowerCase();const status=(st.includes('pago')&&!st.includes('não'))?'pago':'pendente';return {id:String(x.id||uid('tx')),tipo,type:tipo==='receita'?'rec':'dep',categoria:x.categoria||x.cat||'Outros',descricao:x.descricao||x.desc||'',data:x.data||x.date||today(),valor,status,paid:status==='pago'?'Pago':'Não pago',clienteId:x.clienteId||'',orcamentoId:x.orcamentoId||'',agendaId:x.agendaId||'',origem:x.origem||'importado'}}
function norm(s){s=s||empty();s.meta=s.meta||{};s.config=s.config||get('oficinaos_config',{});s.clientes=Array.isArray(s.clientes)?s.clientes:[];s.veiculos=Array.isArray(s.veiculos)?s.veiculos:[];s.orcamentos=Array.isArray(s.orcamentos)?s.orcamentos:[];s.agenda=Array.isArray(s.agenda)?s.agenda:[];s.financeiro=s.financeiro||{};s.financeiro.lancamentos=Array.isArray(s.financeiro.lancamentos)?s.financeiro.lancamentos:[];s.financeiro.lancamentos=s.financeiro.lancamentos.map(tx);const ids=new Set();s.financeiro.lancamentos=s.financeiro.lancamentos.filter(t=>{if(ids.has(t.id))return false;ids.add(t.id);return true});s.financeiro.receitas=s.financeiro.lancamentos.filter(t=>t.tipo==='receita');s.financeiro.despesas=s.financeiro.lancamentos.filter(t=>t.tipo==='despesa');s.financeiro.receber=s.financeiro.receitas.filter(t=>t.status!=='pago');s.financeiro.pagar=s.financeiro.despesas.filter(t=>t.status!=='pago');const receitas=s.financeiro.receitas.reduce((a,b)=>a+n(b.valor),0),despesas=s.financeiro.despesas.reduce((a,b)=>a+n(b.valor),0),pagas=s.financeiro.receitas.filter(t=>t.status==='pago').reduce((a,b)=>a+n(b.valor),0),osEnt=s.agenda.filter(o=>String(o.status||'').toLowerCase().includes('entreg')).length;const ticket=osEnt?pagas/osEnt:(s.financeiro.receitas.length?receitas/s.financeiro.receitas.length:0);const margem=receitas?((receitas-despesas)/receitas*100):0;s.relatorios={ultimoResumo:{receitas,despesas,resultado:receitas-despesas,receitasPagas:pagas,clientes:s.clientes.length,orcamentos:s.orcamentos.length,osTotal:s.agenda.length,osEntregues:osEnt,ticketMedio:ticket,margem,updatedAt:new Date().toISOString()}};s.metas=s.metas||{};s.metas.objetivos=s.metas.objetivos||{faturamento:15000,margem:25,ticketMedio:1800};s.metas.realizado={faturamento:receitas,margem,ticketMedio:ticket,osEntregues:osEnt,resultado:receitas-despesas};s.ia=s.ia||{};s.ia.contexto=[{tipo:'resumo_real',dados:s.relatorios.ultimoResumo}];s.meta.version=VERSION;s.meta.updatedAt=new Date().toISOString();return s}
function load(){let s=get(KEY,null);if(!s){for(const k of ALL_KEYS){s=get(k,null);if(s)break}}if(!s)s=empty();return norm(s)}
function save(s){s=norm(s);set(KEY,s);set('OFICINAOS_STATE_REAL',s);set('OFICINAOS_STATE',s);set('STATE',s);set('ALL_TX',s.financeiro.lancamentos.map(t=>({id:t.id,type:t.type,cat:t.categoria,desc:t.descricao,date:t.data,val:t.valor,paid:t.paid,clienteId:t.clienteId,orcamentoId:t.orcamentoId,agendaId:t.agendaId,origem:t.origem})));return s}
function extract(obj){let s=empty();function mergeState(o){if(!o||typeof o!=='object')return;if(Array.isArray(o.clientes))s.clientes=o.clientes;if(Array.isArray(o.veiculos))s.veiculos=o.veiculos;if(Array.isArray(o.orcamentos))s.orcamentos=o.orcamentos;if(Array.isArray(o.agenda))s.agenda=o.agenda;if(o.financeiro&&Array.isArray(o.financeiro.lancamentos))s.financeiro.lancamentos=o.financeiro.lancamentos;if(Array.isArray(o.ALL_TX))s.financeiro.lancamentos=o.ALL_TX;if(Array.isArray(o.lancamentos))s.financeiro.lancamentos=o.lancamentos}
 if(obj.localStorage){Object.entries(obj.localStorage).forEach(([k,v])=>{try{const parsed=JSON.parse(v);if(k==='ALL_TX'||k.toLowerCase().includes('financeiro')){if(Array.isArray(parsed))s.financeiro.lancamentos=s.financeiro.lancamentos.concat(parsed)}mergeState(parsed)}catch(e){}})}
 mergeState(obj.state);mergeState(obj.STATE);mergeState(obj.OFICINAOS_STATE);mergeState(obj);
 if(Array.isArray(obj))s.financeiro.lancamentos=obj;
 return norm(s)}
function importBackup(obj){const s=extract(obj);save(s);return s}
function clearAll(){Object.keys(localStorage).forEach(k=>{if(k!=='oficinaos_config')localStorage.removeItem(k)});sessionStorage.clear();save(empty())}
function addCliente(c){const s=load();c.id=c.id||uid('cli');c.historico=c.historico||[];s.clientes.push(c);return save(s)}
function addOrcamento(o){const s=load();o.id=o.id||uid('orc');o.status=o.status||'aberto';o.criadoEm=new Date().toISOString();s.orcamentos.push(o);return save(s)}
function aprovarOrcamento(id){const s=load();const o=s.orcamentos.find(x=>x.id===id);if(!o)return s;o.status='aprovado';s.financeiro.lancamentos.push({id:'tx_'+o.id,tipo:'receita',categoria:'Orçamento aprovado',descricao:(o.cliente||'Cliente')+' — '+(o.servico||''),data:today(),valor:n(o.valor),status:'pendente',orcamentoId:o.id,origem:'orcamento'});s.agenda.push({id:'os_'+o.id,cliente:o.cliente,veiculo:o.veiculo,servico:o.servico,valor:n(o.valor),status:'agendado',etapa:'Entrada',entrada:today(),orcamentoId:o.id,origem:'orcamento',fotos:[],historico:[]});return save(s)}
function addOS(o){const s=load();o.id=o.id||uid('os');o.status=o.status||'agendado';o.etapa=o.etapa||'Entrada';o.entrada=o.entrada||today();o.fotos=o.fotos||[];o.historico=o.historico||[];s.agenda.push(o);return save(s)}
function addTx(t){const s=load();s.financeiro.lancamentos.push(t);return save(s)}
function status(txt){let el=document.getElementById('status');if(el)el.textContent=txt+' · '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
window.OSCORE={load,save,importBackup,clearAll,addCliente,addOrcamento,aprovarOrcamento,addOS,addTx,money,n,status};
})();
