
/* OficinaOS V547.00 FINAL CLEAN BUILD — núcleo leve */
(function(){
'use strict';
const KEYS={clientes:'OFICINAOS_CLIENTES',veiculos:'OFICINAOS_VEICULOS',orcamentos:'OFICINAOS_ORCAMENTOS_MIN',agenda:'OFICINAOS_AGENDA_MIN',financeiro:'OFICINAOS_FINANCEIRO_MIN',metas:'OFICINAOS_METAS_MIN',config:'OFICINAOS_CONFIG',last:'OFICINAOS_LAST_BACKUP'};
function parse(v,f){try{return JSON.parse(v||'')}catch(e){return f}}
function get(k,f){return parse(localStorage.getItem(k),f)}
function set(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){alert('Erro ao salvar: '+e.message);return false}}
function n(v){if(v===null||v===undefined||v==='')return 0;if(typeof v==='string')v=v.replace(/R\$/g,'').replace(/\s/g,'').replace(/\./g,'').replace(',','.');v=Number(v);return Number.isFinite(v)?v:0}
function uid(p){return (crypto&&crypto.randomUUID)?crypto.randomUUID():p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)}
function normTx(t){t=t||{};let tipo=String(t.tipo||t.type||'').toLowerCase(); if(tipo==='rec')tipo='receita'; if(tipo==='dep')tipo='despesa'; if(!tipo)tipo='receita'; let status=String(t.status||t.paid||'pendente').toLowerCase(); if(status==='pago')status='pago'; else if(status.includes('pago')&&!status.includes('não'))status='pago'; else status='pendente'; return {id:t.id||uid('tx'),tipo,type:tipo==='receita'?'rec':'dep',descricao:t.descricao||t.desc||t.nome||'',categoria:t.categoria||t.cat||'Geral',data:t.data||t.date||new Date().toISOString().slice(0,10),valor:n(t.valor!==undefined?t.valor:t.val),status,paid:status==='pago'?'Pago':'Não pago',clienteId:t.clienteId||'',orcamentoId:t.orcamentoId||'',agendaId:t.agendaId||'',origem:t.origem||'v547'}}
function load(){let financeiro=get(KEYS.financeiro,{lancamentos:[]});financeiro.lancamentos=Array.isArray(financeiro.lancamentos)?financeiro.lancamentos.map(normTx):[];financeiro.receitas=financeiro.lancamentos.filter(t=>t.tipo==='receita');financeiro.despesas=financeiro.lancamentos.filter(t=>t.tipo==='despesa');financeiro.receber=financeiro.receitas.filter(t=>t.status!=='pago');financeiro.pagar=financeiro.despesas.filter(t=>t.status!=='pago');return {version:'V547.00 FINAL CLEAN BUILD',clientes:get(KEYS.clientes,[]),veiculos:get(KEYS.veiculos,[]),orcamentos:get(KEYS.orcamentos,[]),agenda:get(KEYS.agenda,[]),financeiro,metas:get(KEYS.metas,{}),config:get(KEYS.config,{})}}
function save(s){s=s||load();set(KEYS.clientes,Array.isArray(s.clientes)?s.clientes:[]);set(KEYS.veiculos,Array.isArray(s.veiculos)?s.veiculos:[]);set(KEYS.orcamentos,Array.isArray(s.orcamentos)?s.orcamentos:[]);set(KEYS.agenda,Array.isArray(s.agenda)?s.agenda:[]);set(KEYS.financeiro,{lancamentos:((s.financeiro&&s.financeiro.lancamentos)||[]).map(normTx)});set(KEYS.metas,s.metas||{});set(KEYS.config,s.config||{});return load()}
function importObj(obj){obj=obj||{};let s=load();function take(path){return path.split('.').reduce((a,k)=>a&&a[k],obj)} let ls=obj.localStorage||null; if(ls){Object.entries(ls).forEach(([k,v])=>{let p=parse(v,null); if(!p)return; if(k==='ALL_TX'&&Array.isArray(p))s.financeiro.lancamentos=p.map(normTx); if(k.includes('FINANCEIRO')&&p.lancamentos)s.financeiro.lancamentos=p.lancamentos.map(normTx);})}
let c=obj.clientes||take('state.clientes')||take('STATE.clientes'); if(Array.isArray(c))s.clientes=c; let v=obj.veiculos||take('state.veiculos')||take('STATE.veiculos'); if(Array.isArray(v))s.veiculos=v; let o=obj.orcamentos||take('state.orcamentos')||take('STATE.orcamentos'); if(Array.isArray(o))s.orcamentos=o; let a=obj.agenda||take('state.agenda')||take('STATE.agenda'); if(a&&Array.isArray(a.os))a=a.os; if(Array.isArray(a))s.agenda=a; let f=obj.financeiro||take('state.financeiro')||take('STATE.financeiro'); if(f&&Array.isArray(f.lancamentos))s.financeiro.lancamentos=f.lancamentos.map(normTx); if(Array.isArray(obj.ALL_TX))s.financeiro.lancamentos=obj.ALL_TX.map(normTx); return save(s)}
function exportBackup(){let s=load();let backup={version:'V547.00 FINAL CLEAN BUILD',exportedAt:new Date().toISOString(),...s};set(KEYS.last,{exportedAt:backup.exportedAt,clientes:s.clientes.length,orcamentos:s.orcamentos.length,agenda:s.agenda.length,lancamentos:s.financeiro.lancamentos.length});let blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='oficinaos_v547_backup_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
function importFile(file){if(!file)return;let r=new FileReader();r.onload=e=>{try{importObj(JSON.parse(e.target.result));alert('Importação concluída. Recarregue a aba se necessário.');location.reload()}catch(err){alert('Erro ao importar: '+err.message)}};r.readAsText(file)}
function clearAll(){if(prompt('Digite LIMPAR para apagar dados locais')!=='LIMPAR')return;Object.values(KEYS).forEach(k=>localStorage.removeItem(k));['OFICINAOS_V549_STATE','OFICINAOS_STATE_MASTER','oficinaos_state','oficinaos_clean_v546_30_financeiro','oficinaos_clean_v546_30_state','oficinaos_clean_v546_30_demo_off','oficinaos_v546_16_3_agenda','ALL_TX'].forEach(k=>localStorage.removeItem(k));alert('Dados limpos.');location.reload()}
function cleanLegacyDemos(){['oficinaos_clean_v546_30_demo_off'].forEach(k=>localStorage.setItem(k,'true'));}
function storageInfo(){let rows=[],total=0;for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i),v=localStorage.getItem(k)||'';rows.push({key:k,chars:k.length+v.length});total+=k.length+v.length}rows.sort((a,b)=>b.chars-a.chars);return {total,mb:(total/1024/1024).toFixed(2),rows}}
window.V547Core={load,save,importObj,importFile,exportBackup,clearAll,cleanLegacyDemos,storageInfo,n,money:v=>n(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})};
window.OFICINAOS_STORAGE=window.OFICINAOS_STORAGE||{load,save,importBackup:importObj,clearAll};
window.OSCORE=window.OSCORE||{load,save,money:v=>V547Core.money(v),n};
})();
