(function(g){'use strict';const VERSION='V700.50';const frames=new Map();
function C(){return g.OficinaOSCore700}
function register(){document.querySelectorAll('iframe[data-module]').forEach(f=>frames.set(f.dataset.module,f))}
function send(name,type,payload){const f=frames.get(name);if(!f)return false;f.contentWindow.postMessage({source:'oficinaos-v700',type,payload:payload||{}},'*');return true}
function view(name,s){if(name==='clientes')return{clientes:s.clientes,veiculos:s.veiculos,orcamentos:s.orcamentos,agenda:s.agenda,financeiro:s.financeiro};if(name==='orcamento')return{clientes:s.clientes,veiculos:s.veiculos,orcamentos:s.orcamentos,agenda:s.agenda,financeiro:s.financeiro};if(name==='agenda')return{clientes:s.clientes,orcamentos:s.orcamentos,agenda:s.agenda,financeiro:s.financeiro};if(name==='financeiro')return{clientes:s.clientes,orcamentos:s.orcamentos,agenda:s.agenda,financeiro:s.financeiro};return s}
function broadcast(){const s=C().getState();frames.forEach((f,n)=>send(n,'STATE_CHANGED',{state:view(n,s),module:n}))}
function navigate(name,command){document.querySelectorAll('iframe[data-module]').forEach(f=>f.classList.toggle('active',f.dataset.module===name));document.querySelectorAll('[data-open]').forEach(b=>b.classList.toggle('active',b.dataset.open===name));location.hash=name;if(command)setTimeout(()=>send(name,'COMMAND',command),80);broadcast()}
function replaceModule(module,p){return C().update(d=>{if(module==='clientes'){d.clientes=Array.isArray(p.clientes)?p.clientes:[];d.veiculos=Array.isArray(p.veiculos)?p.veiculos:d.veiculos}if(module==='orcamento')d.orcamentos=Array.isArray(p.orcamentos)?p.orcamentos:d.orcamentos;if(module==='agenda'){d.agenda.os=Array.isArray(p.os)?p.os:[];d.agenda.eventos=Array.isArray(p.eventos)?p.eventos:d.agenda.eventos}if(module==='financeiro'){d.financeiro.lancamentos=Array.isArray(p.lancamentos)?p.lancamentos:[];d.financeiro.contas=Array.isArray(p.contas)?p.contas:d.financeiro.contas}if(module==='metas')d.metas=Object.assign({},d.metas,p);if(module==='ia')d.ia=Object.assign({},d.ia,p);return d},'MODULE_REPLACED',{module})}
async function route(m){const p=m.payload||{};if(m.type==='MODULE_READY'){broadcast();return true}if(m.type==='NAVIGATE'){navigate(p.module,p.command);return true}if(m.type==='CLIENT_CREATE')return C().createCliente(p);if(m.type==='ORC_CREATE')return C().createOrcamento(p);if(m.type==='ORC_UPSERT')return C().upsertOrcamento(p);if(m.type==='ORC_APPROVE')return C().approveOrcamento(p.id,p.options||{});if(m.type==='OS_FINISH')return C().finishOS(p.id,p.options||{});if(m.type==='AGENDA_OS_UPSERT')return C().upsertAgendaOS(p);if(m.type==='FINANCEIRO_REPLACE')return C().replaceFinanceiro(p.lancamentos,p.contas);if(m.type==='METAS_UPDATE')return C().updateMetas(p);if(m.type==='MODULE_REPLACE')return replaceModule(m.module,p);if(m.type==='JSON_IMPORT')return C().importJSON(p);return null}
function start(){register();g.addEventListener('message',e=>{const m=e.data||{};if(m.source!=='oficinaos-module-v700')return;route(m).then(r=>{if(m.requestId)e.source.postMessage({source:'oficinaos-v700',type:'RESPONSE',requestId:m.requestId,payload:r},'*')}).catch(err=>e.source.postMessage({source:'oficinaos-v700',type:'ERROR',requestId:m.requestId,payload:{message:err.message}},'*'))});C().subscribe(()=>broadcast());document.querySelectorAll('iframe[data-module]').forEach(f=>f.addEventListener('load',broadcast));broadcast();return true}
g.OficinaOSIntegration700={VERSION,start,broadcast,navigate,send,route};})(window);