
(function(g){
'use strict';
const templates=[['limaprata_premium','Limaprata Premium'],['oficinaos_tecnico','OficinaOS Técnico'],['clean','Clean'],['laudo_fotografico','Laudo Fotográfico'],['checklist_entrega','Checklist de Entrega'],['historico_veiculo','Histórico do Veículo']];
function currentId(){let s=g.DocumentStateConnector?g.DocumentStateConnector.getState():{};return(s.orcamentoAtual&&(s.orcamentoAtual.id||s.orcamentoAtual.numero))||(s.orcamentos&&s.orcamentos.length&&(s.orcamentos[s.orcamentos.length-1].id||s.orcamentos[s.orcamentos.length-1].numero))||''}
function html(){return'<div id="documentCenter" class="doc-center-inline" style="background:#fff;border:1px solid rgba(100,60,20,.18);border-left:4px solid #b8621a;border-radius:10px;padding:12px;margin:12px 0;box-shadow:0 2px 10px rgba(150,80,20,.08)"><div style="font-weight:800;letter-spacing:.08em;margin-bottom:8px">GERAR DOCUMENTO</div><select id="dcTemplate" style="width:100%;padding:8px;margin-bottom:8px">'+templates.map(t=>'<option value="'+t[0]+'">'+t[1]+'</option>').join('')+'</select><div style="display:flex;gap:6px;flex-wrap:wrap"><button id="dcPreview" type="button">Visualizar</button><button id="dcPrint" type="button">Imprimir/PDF</button><button id="dcWhatsApp" type="button">WhatsApp</button><button id="dcDownload" type="button">Baixar HTML</button><button id="dcHistory" type="button">Salvar Histórico</button></div></div>'}
function target(){let cand=Array.from(document.querySelectorAll('section,article,div,aside')).find(el=>{let t=el.textContent||'';return t.length<3500&&(/orçamento para cliente/i.test(t)||/gerar pdf/i.test(t)||/salvar orçamento/i.test(t)||/histórico/i.test(t))});return cand||document.querySelector('#orcamento')||document.querySelector('[id*="orcamento" i]')||document.body}
function buildUI(){let old=document.getElementById('documentCenter');if(old)old.remove();let w=document.createElement('div');w.innerHTML=html();target().appendChild(w.firstElementChild);bind()}
function buildDoc(){let tpl=document.getElementById('dcTemplate')?.value||'limaprata_premium',doc=g.DocumentModelCore.build(currentId(),tpl);if(g.QREngine)doc=g.QREngine.attach(doc);return{doc,tpl}}
function preview(){let x=buildDoc(),h=g.RenderEngine.preview(x.doc,x.tpl),w=window.open('','_blank');if(!w){alert('Pop-up bloqueado.');return}w.document.open();w.document.write(h);w.document.close()}
function printDoc(){let x=buildDoc();g.RenderEngine.print(x.doc,x.tpl)}
function download(){let x=buildDoc(),h=g.RenderEngine.preview(x.doc,x.tpl),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([h],{type:'text/html'}));a.download='oficinaos_'+x.tpl+'_'+(x.doc.orcamento?.numero||x.doc.orcamento?.id||'documento')+'.html';a.click()}
function saveHistory(){let x=buildDoc(),r=g.DocumentStateConnector.saveDocumentHistory(x.doc,{template:x.tpl,status:'gerado'});alert('Documento salvo no histórico: '+r.id)}
function whatsapp(){let x=buildDoc(),d=x.doc,tel=String(d.cliente?.whatsapp||d.cliente?.telefone||'').replace(/\D/g,''),msg='Olá '+(d.cliente?.nome||'')+'. Segue seu orçamento '+(d.orcamento?.numero||d.orcamento?.id||'')+' - '+(d.empresa?.nome||'OficinaOS')+'. Total: '+new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(d.orcamento?.financeiro?.total||0))+'.',url=tel?'https://wa.me/55'+tel+'?text='+encodeURIComponent(msg):'https://wa.me/?text='+encodeURIComponent(msg);window.open(url,'_blank');g.DocumentStateConnector.saveDocumentHistory(d,{template:x.tpl,status:'enviado_whatsapp'})}
function bind(){[['dcPreview',preview],['dcPrint',printDoc],['dcDownload',download],['dcHistory',saveHistory],['dcWhatsApp',whatsapp]].forEach(x=>{let e=document.getElementById(x[0]);if(e)e.onclick=x[1]})}
function refresh(){buildUI()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh);else refresh();
g.DocumentCenter={open:refresh,refresh,preview,download,saveHistory,whatsapp};
})(window);
